[workspace]
authors = ["luckyjim <jcolley@lpnhe.in2p3.fr>"]
channels = ["conda-forge"]
name = "bind_template"
platforms = ["linux-64"]
version = "0.1.0"


[feature.runtime.dependencies]
nanobind = ">=2.13.0,<3"
python = ">=3.14.6,<3.15"
ipython = ">=9.15.0,<10"
pip = ">=26.1.2,<27"
numpy = ">=2.5.0,<3"
scipy = ">=1.18.0,<2"

[feature.test.dependencies]
pytest = "*"
pytest-cov = ">=7.1.0,<8"
ruff = ">=0.15.20,<0.16"

[feature.test.tasks]
install = "pip install -e . "
tests_unit = "pytest -v --cov=bind_template tests/unit"

[feature.lint.dependencies]
ruff = "*"

[feature.lint.tasks]
format = "ruff format src/bind_template && ruff check --select I --fix src/bind_template"
lint = "ruff check src/bind_template"
fix_code = "ruff check --fix src/bind_template"

[environments]
default = { features = ["runtime"] }
quality = { features = ["runtime","test","lint"] }
